services:
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql